const Homeproduct =
[
    {
        id:1,
        Name:'product1',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/Laptop1.png',
        cat:'laptop',
        type:'new',
    },
    {
        id:2,
        Name:'product2',
        price:'96',
        img: process.env.PUBLIC_URL +'/image/Laptop2.png',
        cat:'laptop',
        type:'new',
    },
    {
        id:3,
        Name:'product3',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/watchMen1.png',
        cat:'watch',
        type:'new',
    },
    {
        id:4,
        Name:'product4',
        price:'636',
        img: process.env.PUBLIC_URL +'/image/watchMen2.png',
        cat:'watch',
        type:'new',
    },
    {
        id:5,
        Name:'product5',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/watchWomen1.png',
        cat:'watch',
        type:'featured',
    },
    {
        id:6,
        Name:'product6',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/watchWomen2.png',
        cat:'watch',
        type:'featured',
    },
    {
        id:7,
        Name:'product7',
        price:'956',
        img: process.env.PUBLIC_URL +'/image/watchMen2.png',
        cat:'watch',
        type:'featured',
    },
     {
        id:8,
        Name:'product8',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/appleWatch.png',
        cat:'watch',
        type:'featured',
    },
     {
        id:9,
        Name:'product9',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/micSpeaker1.png',
        cat:'speaker',
        type:'top',
    },
     {
        id:10,
        Name:'product10',
        price:'26',
        img: process.env.PUBLIC_URL +'/image/speakerJBL.png',
        cat:'speaker',
        type:'top',
    }
]

export default Homeproduct;